# -*- coding: utf-8 -*-
"""
Rocket.py


"""
import io
import os
import sys
import numpy as np
import imageio as iio
from PIL import Image
from matplotlib import pyplot as plt
from symbols import deg_symbol, eta_symbol, gamma_symbol
import numerical_tools as nt
import geophysical_tools as gt
import coordinate_conversion_tools as cct


class RocketStage():
    def __init__(self,
                 name,
                 m_empty,
                 m_propellant,
                 m_dot,
                 v_exhaust,
                 p_exhaust,
                 A_exit,
                 stage_diameter_m,
                 coast_duration_sec,
                 t_steer_start_rel,
                 steer_duration_sec,
                 target_fpa_at_bo_deg):
        
        self.name = name
        self.m_empty = m_empty
        self.m_propellant = m_propellant
        self.m_dot = m_dot
        self.v_exhaust = v_exhaust
        self.p_exhaust = p_exhaust
        self.A_exit = A_exit
        self.stage_diameter_m = stage_diameter_m
        self.t_steer_start_rel = t_steer_start_rel #steer start time relative to engine start, with engine starting AFTER the coast duration
        
        self.target_fpa_at_bo_deg = target_fpa_at_bo_deg
        self.coast_duration_sec = coast_duration_sec
        
        #Derived variables
        self.A = np.pi * (self.stage_diameter_m)**2 / 4
        self.engine_burn_duration_sec = self.m_propellant/self.m_dot #sec, burnout time relative to stage's engine start
        
        if steer_duration_sec > self.engine_burn_duration_sec:
            self.steer_duration_sec = self.engine_burn_duration_sec
        elif steer_duration_sec == -1:
            self.steer_duration_sec = self.engine_burn_duration_sec
        else:
            self.steer_duration_sec = steer_duration_sec
            
        #Variables to be computed upon program execution
        self.required_eta_deg = None #temporary, should be None
        self.fpa_at_bo_deg = None #temporary, should be None
        self.t_start_abs = None #absolute start time, i.e. start time relative to t-0
        self.t_bo_abs = None #absolute burnout time
        self.m_other = None #kg, the mass of all other upper stages and payload
        self.time_and_thrust_arrays = None #N, thrust generated by the engines (for plotting purposes)
        
def null_config():
	return {
        'name'               : 'null',
		'datetime0'          : '2020-01-01 00:12:00', #initial UT1 date-time; format: year-month-day hours:minutes:seconds
		'frame'              : 'J2000',      #standard for earth-centered propagation
		'ode_solver'         : 'rk4',
        'lla0'               : np.array([0,0,0]), #Latitude [degrees], Longitude [degrees], altitude [meters]
        'v0_rel'             : np.array([0,0,0]), #vx [m/s], vy [m/s], vz [m/s]
		'stages'             : [],
        'tspan'              : 0,
        'dt'                 : 0,
        'm_payload'          : 0,
        'launch_azimuth_deg' : 0,
		'output_dir'         : os.getcwd() + r'\Media',
	}

class Rocket():
    def __init__(self,config):
        self.config = null_config()
        for key in config.keys():
            self.config[key] = config[key]
        
        #If the output directory doesn't exist, create it
        if not os.path.exists(self.config['output_dir']): 
            os.mkdir(self.config['output_dir'])
        
        # Make an output directory for the rocket object
        self.config['output_dir'] += fr'\{self.config['name'].replace(' ','')}'
        if not os.path.exists(self.config['output_dir']):
            os.mkdir(self.config['output_dir'])
            
        if self.config['lla0'][0] !=0:
            print(f"ERROR: for this 2D rocket simulation, the launch site latitude should be set to 0{deg_symbol}! Right now, the {self.config['name']} launch site latitude is set to {self.config['lla0'][0]}{deg_symbol}. Please set {self.config['name']} launch site latitude to 0{deg_symbol}!")
            sys.exit(1) #end program with exit code 1
            
        if abs(self.config['launch_azimuth_deg']) != 90:
            print(f"ERROR: for this 2D rocket simulation, the launch azimuth should be either 90 or -90 degrees! Right now, launch_azimuth_deg = {self.config['launch_azimuth_deg']}")
            sys.exit(1) #end program with exit code 1
            
        #If the coast time of the first stage is set to a non-zero value, warn the user to check the inputs and end the program
        if self.config['stages'][0].coast_duration_sec != 0:
            print(f"ERROR: the {self.config['name']} first stage coast time is {self.config['stages'][0].coast_duration_sec} sec while it should be 0! Please review your stage configurations.")
            sys.exit(1) #end program with exit code 1
        
        self.lat0_deg = self.config['lla0'][0]
        self.lon0_deg = self.config['lla0'][1]
        self.alt0_m = self.config['lla0'][2]
        self.gmst0_rad = cct.ut1_to_gmst(self.config['datetime0'])
        self.r0,self.v0 = cct.lla_to_eci(self.lat0_deg,self.lon0_deg,self.alt0_m,self.config['v0_rel'],self.gmst0_rad)
        
        self.solve_stage_times()
        self.solve_stage_mass_other()
        
        self.m0 = self.config['stages'][0].m_empty + self.config['stages'][0].m_propellant + self.config['stages'][0].m_other
        self.state0 = [self.r0[0],self.r0[1],self.v0[0],self.v0[1],self.m0] #initial state vector
        
        states,metrics = nt.propagate_traj(self.state0,
                                           self.config['tspan'],
                                           self.config['dt'],
                                           self.config['stages'],
                                           self.config['launch_azimuth_deg'],
                                           self.config['payload_separates'],
                                           self.config['ode_solver'],
                                           get_metrics=True)
        
        self.rx = states[0]
        self.ry = states[1]
        self.rz = np.zeros(len(self.rx))
        self.vx = states[2]
        self.vy = states[3]
        self.vz = np.zeros(len(self.vx))
        self.m =  states[4]

        self.ax_grav = metrics[0]
        self.ay_grav = metrics[1]
        self.ax_thrust = metrics[2]
        self.ay_thrust = metrics[3]
        self.ax_drag = metrics[4]
        self.ay_drag = metrics[5]
        self.Cd = metrics[6]
        self.M = metrics[7]
        self.fpa_deg = metrics[8]
        self.eta_deg = metrics[9]
        self.dynamic_pressure = metrics[10]
        
        self.ax = self.ax_grav + self.ax_thrust + self.ax_drag
        self.ay = self.ay_grav + self.ay_thrust + self.ay_drag
        self.az = np.zeros(len(self.ax))
        self.fpa_rad = self.fpa_deg * np.pi/180
        
        self.r = np.column_stack((self.rx,self.ry,self.rz))
        self.v = np.column_stack((self.vx,self.vy,self.vz))
        self.a = np.column_stack((self.ax,self.ay,self.az))
        
        self.times = np.arange(0,self.config['tspan']+self.config['dt']/2,self.config['dt'])[:len(states[0])]

        GMST_vec = cct.get_gmsts(self.config['datetime0'],self.times)
        self.r_ecef,self.v_ecef = cct.eci_to_ecef_vec(self.r, self.v, GMST_vec)
        
        self.rx_ecef = self.r_ecef[:,0]
        self.ry_ecef = self.r_ecef[:,1]
        self.rz_ecef = self.r_ecef[:,2]

        self.altitudes_km = gt.get_altitudes_km(self.rx,self.ry,self.rz)
        self.ground_range_km = gt.get_ground_ranges_km(self.lat0_deg,self.lon0_deg,self.config['datetime0'],self.rx,self.ry,self.rz,self.times)
        self.v_rad = nt.get_radial_vel(self.r,self.v)
        self.v_tan = nt.get_tangential_vel(self.r,self.v)
        self.v_rad_ecef = nt.get_radial_vel(self.r_ecef,self.v_ecef)
        self.v_tan_ecef = nt.get_tangential_vel(self.r_ecef,self.v_ecef)
        self.a_rad = nt.get_radial_accel(self.r,self.a)
        self.a_tan = nt.get_tangential_accel(self.r,self.a)
        
        self.lla_final = cct.eci_to_lla([self.rx[-1],self.ry[-1],self.rz[-1]],cct.get_current_gmst(self.config['datetime0'],self.times[-1]))
        
        self.stage_count = len(self.config['stages'])
        self.t_bo_final = round(self.config['stages'][self.stage_count-1].t_bo_abs)
        idx_t_bo_final = round(self.t_bo_final/self.config['dt'])
        self.v_tan_bo = self.v_tan[idx_t_bo_final] #tangential velocity at final stage burnout
        
        self.output_msg_displayed_once = False
        self.phase_t_idx_dict = self.get_phase_time_index_dict()
        
        for stage in self.config['stages']:
            stage.time_and_thrust_arrays = self.get_stage_time_and_thrust_arrays(stage)
            
        
    def get_t_idx(self,t):
        t_idx = round(t/self.config['dt'])
        return t_idx
    
    def get_stage_time_and_thrust_arrays(self,stage):
        t_arr_abs = np.arange(stage.t_start_abs,stage.t_bo_abs+self.config['dt']/2,self.config['dt']) #sec, time array
        T_arr = np.zeros(len(t_arr_abs)) #N, thrust array
        for idx1,t in enumerate(t_arr_abs):
            idx2 = self.get_t_idx(t)
            T_arr[idx1] = stage.v_exhaust * stage.m_dot + (stage.p_exhaust - gt.get_air_pressure(self.altitudes_km[idx2])) * stage.A_exit
        t_arr_rel = np.arange(0,stage.t_bo_abs-stage.t_start_abs+self.config['dt']/2,self.config['dt']) #sec, time array
        return [t_arr_rel,T_arr]
    
    def get_phase_time_index_dict(self,end_is_bo=False):
        #Populate the phase time index dictionary
        phase_t_idx_dict = {}

        for i,stage in enumerate(self.config['stages'],1):
            if i == 1:
                phase_t_idx_dict['vertical flight'] = [self.get_t_idx(stage.t_start_abs),self.get_t_idx(stage.t_start_abs+stage.t_steer_start_rel)]
                phase_t_idx_dict['pitch over'] = [self.get_t_idx(stage.t_start_abs+stage.t_steer_start_rel),self.get_t_idx(stage.t_start_abs+stage.t_steer_start_rel+stage.steer_duration_sec)]
                phase_t_idx_dict['gravity turn'] = [self.get_t_idx(stage.t_start_abs+stage.t_steer_start_rel+stage.steer_duration_sec),self.get_t_idx(stage.t_bo_abs)-1]
            elif i == 2:
                phase_t_idx_dict['MECO, stage sep.'] = [self.get_t_idx(stage.t_start_abs)-1,self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec)]
                phase_t_idx_dict['2nd stage burn'] = [self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec),self.get_t_idx(stage.t_bo_abs)-1]
            elif i == 3:
                phase_t_idx_dict['SECO, stage sep.'] = [self.get_t_idx(stage.t_start_abs)-1,self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec)]
                phase_t_idx_dict['3rd stage burn'] = [self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec),self.get_t_idx(stage.t_bo_abs)-1]
            elif i == 4:
                phase_t_idx_dict['TECO, stage sep.'] = [self.get_t_idx(stage.t_start_abs)-1,self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec)]
                phase_t_idx_dict['3rd stage burn'] = [self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec),self.get_t_idx(stage.t_bo_abs)-1]
            else:
                phase_t_idx_dict[f'S{i} ECO, stage sep.'] = [self.get_t_idx(stage.t_start_abs)-1,self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec)]
                phase_t_idx_dict[f'{i}th stage burn'] = [self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec),self.get_t_idx(stage.t_bo_abs)-1]
            if i == len(self.config['stages']):
                if i == 1:
                    if self.config['payload_separates'] == True:
                        phase_t_idx_dict['MECO, stage sep.'] = [self.get_t_idx(stage.t_bo_abs)-1,self.get_t_idx(stage.t_bo_abs)]
                        phase_t_idx_dict['coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                    else:
                        phase_t_idx_dict['MECO, coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                elif i == 2:
                    if self.config['payload_separates'] == True:
                        phase_t_idx_dict['SECO, stage sep.'] = [self.get_t_idx(stage.t_bo_abs)-1,self.get_t_idx(stage.t_bo_abs)]
                        phase_t_idx_dict['coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                    else:
                        phase_t_idx_dict['SECO, coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                elif i == 3:
                    if self.config['payload_separates'] == True:
                        phase_t_idx_dict['TECO, stage sep.'] = [self.get_t_idx(stage.t_bo_abs)-1,self.get_t_idx(stage.t_bo_abs)]
                        phase_t_idx_dict['coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                    else:
                        phase_t_idx_dict['TECO, coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                elif i == 4:
                    if self.config['payload_separates'] == True:
                        phase_t_idx_dict['FECO, stage sep.'] = [self.get_t_idx(stage.t_bo_abs)-1,self.get_t_idx(stage.t_bo_abs)]
                        phase_t_idx_dict['coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                    else:
                        phase_t_idx_dict['FECO, coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                else:
                    if self.config['payload_separates'] == True:
                        phase_t_idx_dict[f'S{i} ECO, stage sep.'] = [self.get_t_idx(stage.t_bo_abs)-1,self.get_t_idx(stage.t_bo_abs)]
                        phase_t_idx_dict['coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                    else:
                        phase_t_idx_dict[f'S{i} ECO, coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                    
        return phase_t_idx_dict
        
    def solve_stage_times(self):
        '''
        This solve for the stage start time using the sum of the coast and engine burn durations of previous stages
        '''
        for i,stage in enumerate(self.config['stages']):
            if i == 0 :
                stage.t_start_abs = 0
                stage.t_bo_abs = stage.t_start_abs + stage.coast_duration_sec + stage.engine_burn_duration_sec
            else:
                stage.t_start_abs = self.config['stages'][i-1].t_bo_abs
                stage.t_bo_abs = stage.t_start_abs + stage.coast_duration_sec + stage.engine_burn_duration_sec
            
    def solve_stage_mass_other(self):
        '''
        This solves for the "other mass" which is the sum of the mass of all the stages above the current stage 
        and the payload mass. Thus, in the simulation the total mass to be used upon staging is:
        m_empty + m_propellant + m_other
        '''
        m_payload = self.config['m_payload']
        stages = self.config['stages']
        for i in range(len(stages)):
            stages[i].m_other = m_payload
            for j in range(i+1,len(self.config['stages'])):
                stages[i].m_other += stages[j].m_empty + stages[j].m_propellant
            #print(f'Stage {i+1} m_other = {stages[i].m_other}')
                
        
    def plot_alt_vs_ground_range(self,output_img=False,show_flight_phases=False):
        fig,ax = plt.subplots()
        
        if show_flight_phases:
            for key in self.phase_t_idx_dict.keys():
                plt.plot(self.ground_range_km[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],self.altitudes_km[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],label=key)
        else:
            plt.plot(self.ground_range_km,self.altitudes_km,'r')
            
        plt.ylim(0, None) 
        plt.title(f'{self.config['name']} Rocket Altitude vs Ground Range\nMax ground range = {round(max(self.ground_range_km),1)}[km], Max altitude = {round(max(self.altitudes_km),1)}[km]')
        plt.xlabel('Ground Range [km]')
        plt.ylabel('Altitude [km]')
        plt.grid(True)
        plt.axis('scaled')
        plt.tight_layout()
        
        fig.draw_without_rendering();
        bbox = ax.get_window_extent() #returns bounding box in pixel coordinates
        #print(f'{self.config['name']} alt_vs_ground_range plot box has width = {bbox.width} and height = {bbox.height}')
        
        if show_flight_phases:
            plt.legend(bbox_to_anchor=(0.5, -.3*bbox.width/bbox.height/3.77), loc="upper center",ncol=2)
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_alt_vs_ground_range.png', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True

    def plot_fpa_vs_time(self,output_img=False):
        plt.figure()
        plt.plot(self.times,self.fpa_deg,'r',label=f'flight path angle, {gamma_symbol} [{deg_symbol}]')
        plt.plot(self.times,self.eta_deg,'g',label=f'steering angle, {eta_symbol} [{deg_symbol}]')
    
        plt.title(f'{self.config['name']} Pitch Program')
        plt.xlabel('Time [s]')
        plt.ylabel(f'Angle [{deg_symbol}]')
        plt.grid(True)
    
        color_dict = {0:'k',1:'c',2:'m'}
        for i,stage in enumerate(self.config['stages']):
            stage_bo_time = stage.t_start_abs + stage.coast_duration_sec + stage.engine_burn_duration_sec
            plt.scatter(stage_bo_time, stage.target_fpa_at_bo_deg, color = color_dict[i],marker='o',s=50,label=f'Stage {i+1} target FPA at $t_{{bo}}$={round(stage_bo_time,1)} [s]',zorder=2)
            x_line_pos = stage.t_start_abs + stage.coast_duration_sec + stage.engine_burn_duration_sec
            plt.axvline(x=x_line_pos, color=color_dict[i], linestyle='--', linewidth=1)
        plt.legend()
        plt.tight_layout()
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_fpa_vs_time.png', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
    
    def plot_alt_vs_time(self,output_img=False,show_flight_phases=False):
        # Altitude vs time
        plt.figure()
        
        if show_flight_phases:
            for key in self.phase_t_idx_dict.keys():
                plt.plot(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],self.altitudes_km[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],label=key)
            plt.legend(bbox_to_anchor=(0.5, -.3), loc="upper center",ncol=2)
        else:
            plt.plot(self.times,self.altitudes_km,'r')
            
        plt.title(f'{self.config['name']} Rocket Altitude vs Time\nMax altitude = {round(max(self.altitudes_km),1)}[km], Impact at t+{round(self.times[-1],2)}[s]')
        plt.xlabel('Time [sec]')
        plt.ylabel('Altitude [km]')
        plt.grid(True)
        plt.tight_layout()

        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_alt_vs_time.png', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
    
    def plot_traj_metrics_eci(self,output_img=False):
        # Position vs time, velocity vs time, and acceleration vs time in ECI frame
        fig, (ax1, ax2, ax3) = plt.subplots(1,3)
        fig.suptitle(f'{self.config['name']} Trajectory Metrics (ECI Frame)', fontsize=16, fontweight="bold",y=1.02)
        
        big_ax = fig.add_subplot(111, frameon=False)
        big_ax.tick_params(labelcolor='none', top=False, bottom=False, left=False, right=False)
        big_ax.grid(False)
    
        ax1.plot(self.times/60, self.ground_range_km, label='ground range')
        ax1.plot(self.times/60, self.altitudes_km, label='altitude')
        ax1.set_title(f'Max ground range = {round(max(self.ground_range_km),1)} [km]\nMax altitude = {round(max(self.altitudes_km),1)} [km]',fontsize=7)
        ax1.set_xlabel('time [min]')
        ax1.set_ylabel('position [km]')
        ax1.legend(
            loc="upper center", 
            bbox_to_anchor=(0.5, -0.15), 
            ncol=1
            )
        ax1.grid()
    
        ax2.plot(self.times/60, self.v_tan/1000, label='tangential vel.')
        ax2.plot(self.times/60, self.v_rad/1000, label='radial vel.')
        ax2.set_title(f'|Max tangential vel| = {round(max(abs(self.v_tan/1000)),1)} [km/s]\n|Max radial vel| = {round(max(abs(self.v_rad/1000)),1)} [km/s]',fontsize=7)
        ax2.set_xlabel('time [min]')
        ax2.set_ylabel('velocity [km/s]')
        ax2.legend(
            loc="upper center", 
            bbox_to_anchor=(0.5, -0.15), 
            ncol=1
            )
        ax2.grid()
    
        ax3.plot(self.times/60, self.a_tan, label='tangential accel.')
        ax3.plot(self.times/60, self.a_rad, label='radial accel.')
        ax3.set_title(f'|Max tangential accel| = {round(max(abs(self.a_tan)),1)} [$m/s^2$]\n|Max radial accel| = {round(max(abs(self.a_rad)),1)} [$m/s^2$]',fontsize=7)
        ax3.set_xlabel('time [min]')
        ax3.set_ylabel(r'acceleration [$m/s^2$]')
        ax3.legend(
            loc="upper center", 
            bbox_to_anchor=(0.5, -0.15), 
            ncol=1
            )
        ax3.grid()
        
        plt.subplots_adjust(hspace=0.5, wspace=0.6)
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_traj_metrics_eci.png', bbox_inches='tight', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
            
    def plot_traj_metrics_ecef(self,output_img=False):
        # Position vs time, velocity vs time, and acceleration vs time in ECEF frame
        fig, (ax1, ax2, ax3) = plt.subplots(1,3)
        fig.suptitle(f'{self.config['name']} Trajectory Metrics (ECEF Frame)', fontsize=16, fontweight="bold",y=1.02)
        
        big_ax = fig.add_subplot(111, frameon=False)
        big_ax.tick_params(labelcolor='none', top=False, bottom=False, left=False, right=False)
        big_ax.grid(False)
    
        ax1.plot(self.times/60, self.ground_range_km, label='ground range')
        ax1.plot(self.times/60, self.altitudes_km, label='altitude')
        ax1.set_title(f'Max ground range = {round(max(self.ground_range_km),1)} [km]\nMax altitude = {round(max(self.altitudes_km),1)} [km]',fontsize=7)
        ax1.set_xlabel('time [min]')
        ax1.set_ylabel('position [km]')
        ax1.legend(
            loc="upper center", 
            bbox_to_anchor=(0.5, -0.15), 
            ncol=1
            )
        ax1.grid()
    
        ax2.plot(self.times/60, self.v_tan_ecef/1000, label='tangential vel.')
        ax2.plot(self.times/60, self.v_rad_ecef/1000, label='radial vel.')
        ax2.set_title(f'|Max tangential vel| = {round(max(abs(self.v_tan_ecef/1000)),1)} [km/s]\n|Max radial vel| = {round(max(abs(self.v_rad_ecef/1000)),1)} [km/s]',fontsize=7)
        ax2.set_xlabel('time [min]')
        ax2.set_ylabel('velocity [km/s]')
        ax2.legend(
            loc="upper center", 
            bbox_to_anchor=(0.5, -0.15), 
            ncol=1
            )
        ax2.grid()
    
        ax3.plot(self.times/60, self.a_tan, label='tangential accel.')
        ax3.plot(self.times/60, self.a_rad, label='radial accel.')
        ax3.set_title(f'|Max tangential accel| = {round(max(abs(self.a_tan)),1)} [$m/s^2$]\n|Max radial accel| = {round(max(abs(self.a_rad)),1)} [$m/s^2$]',fontsize=7)
        ax3.set_xlabel('time [min]')
        ax3.set_ylabel(r'acceleration [$m/s^2$]')
        ax3.legend(
            loc="upper center", 
            bbox_to_anchor=(0.5, -0.15), 
            ncol=1
            )
        ax3.grid()
        
        plt.subplots_adjust(hspace=0.5, wspace=0.6)
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_traj_metrics_ecef.png', bbox_inches='tight', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
    
    def plot_dyn_pres_vs_time(self,output_img=False,show_flight_phases=False):
        plt.figure()
        
        if show_flight_phases:
            for key in self.phase_t_idx_dict.keys():
                plt.plot(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],self.dynamic_pressure[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]/1000,label=key)
            plt.legend()
        else:
            plt.plot(self.times,self.dynamic_pressure/1000,'r')
            
        plt.title(f'{self.config['name']} Dynamic Pressure vs Time')
        plt.grid(True)
        plt.xlabel('time [s]')
        plt.ylabel(r'dynamic pressure [KPa]')
        plt.tight_layout()
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_dyn_pres_vs_time.png', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
    
    def plot_mass_vs_time(self,output_img=False,show_flight_phases=False):
        plt.figure()
        
        if show_flight_phases:
            for key in self.phase_t_idx_dict.keys():
                plt.plot(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],self.m[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],label=key)
            plt.legend()
        else:
            plt.plot(self.times,self.m,'r')
            
        plt.title(f'{self.config['name']} Mass vs Time')
        plt.grid(True)
        plt.xlabel('time [s]')
        plt.ylabel('mass [kg]')
        plt.tight_layout()
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_mass_vs_time.png', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
    
    def plot_mach_vs_time(self,output_img=False,show_flight_phases=False):
        plt.figure()
        
        if show_flight_phases:
            for key in self.phase_t_idx_dict.keys():
                plt.plot(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],self.M[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],label=key)
            plt.legend()
        else:
            plt.plot(self.times, self.M,'r')
            
        plt.xlabel('time [s]')
        plt.ylabel('Mach number')
        plt.title(f'{self.config['name']} Mach Number vs Time')
        plt.grid(True)
        plt.tight_layout()
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_mach_vs_time.png', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
            
    def plot_cd_vs_time(self,output_img=False,show_flight_phases=False):
        plt.figure()
        
        if show_flight_phases:
            for key in self.phase_t_idx_dict.keys():
                plt.plot(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],self.Cd[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],label=key)
            plt.legend()
        else:
            plt.plot(self.times,self.Cd,'b')
            
        plt.xlabel('time [s]')
        plt.ylabel('drag coefficient')
        plt.title(f'{self.config['name']} Drag Coefficient vs Time')
        plt.grid(True)
        plt.tight_layout()
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_cd_vs_time.png', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True

    def plot_2d_traj_eci(self,output_img=False,output_gif=False,gif_frame_count=30,ms_per_frame=100,show_flight_phases=False):

        #If its a short range trajectory, show plots relative to the launch point
        if max(self.ground_range_km) < 2000:
            rel_to_launch_point = True
        else:
            rel_to_launch_point = False
                

        if rel_to_launch_point == True:
            #Generate plot of vertical distance vs horizontal distance from ECEF launch point across limb of earth
            limb_of_earth = plt.Circle((0, -gt.R_eq/1000), gt.R_eq/1000, color='b',zorder=0)
            fig, ax1 = plt.subplots()
            ax1.add_patch(limb_of_earth)
            
            #Compute the ECI coordinates of the true launch point
            GMST_rad = cct.get_current_gmst(self.config['datetime0'],self.times[-1])
            r_true_launch_pt,_ = cct.lla_to_eci(self.lat0_deg,self.lon0_deg,self.alt0_m,np.array([0,0,0]),GMST_rad)
            rx_true_launch_pt = r_true_launch_pt[0]
            ry_true_launch_pt = r_true_launch_pt[1]
    
            #rotate the coordinates by longitude and GMST to make the plot horizontal
            rotation_angle_rad = -(np.radians(self.lon0_deg) + self.gmst0_rad) + np.pi/2
            R = np.array([[np.cos(rotation_angle_rad),-np.sin(rotation_angle_rad)],[np.sin(rotation_angle_rad),np.cos(rotation_angle_rad)]])
            r_vec = np.array([self.rx,self.ry])
            r_true_launch_pt_vec = np.array([rx_true_launch_pt,ry_true_launch_pt])
            r_vec_new = np.matmul(R,r_vec)
            r_true_launch_pt_vec_new = np.matmul(R,r_true_launch_pt_vec)
            rx_new = r_vec_new[0]
            ry_new = r_vec_new[1]
            rx_true_launch_pt_new = r_true_launch_pt_vec_new[0]
            ry_true_launch_pt_new = r_true_launch_pt_vec_new[1]
            if (rx_new[-1] < 0):
                rx_new = -rx_new
                rx_true_launch_pt_new = -rx_true_launch_pt_new
                
            if show_flight_phases == True:
                for key in self.phase_t_idx_dict.keys():
                    ax1.plot(rx_new[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]/1000,(ry_new[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]-gt.R_eq)/1000,label=key)
            else:
                ax1.plot(rx_new/1000,(ry_new-gt.R_eq)/1000,'r', zorder=2)
                
            ax1.scatter(rx_new[0]/1000,(ry_new[0]-gt.R_eq)/1000,c='cyan',marker='.',s=50,label='launch point', zorder=3)
            ax1.scatter(rx_true_launch_pt_new/1000,(ry_true_launch_pt_new-gt.R_eq)/1000,c='tab:pink',marker='.',s=50,label='true launch point', zorder=3)
            if self.altitudes_km[-1] < 2:
                ax1.scatter(rx_new[-1]/1000,(ry_new[-1]-gt.R_eq)/1000,c='yellow',marker='.',s=50,label='impact point', zorder=3)
            elif self.altitudes_km[-1] > 2:
                ax1.scatter(rx_new[-1]/1000,(ry_new[-1]-gt.R_eq)/1000,c='orange',marker='.',s=50,label='final point', zorder=3)
            ax1.set_xlim((min(rx_new) - .25*(max(rx_new)-min(rx_new)))/1000,(max(rx_new) + .25*(max(rx_new)-min(rx_new)))/1000)
            ax1.set_ylim((min(ry_new-gt.R_eq) - .25*(max(ry_new-gt.R_eq)-min(ry_new-gt.R_eq)))/1000,(max(ry_new-gt.R_eq) + .25*(max(ry_new-gt.R_eq)-min(ry_new-gt.R_eq)))/1000)
            ax1.set_xlabel('Horizontal dist. from ECI launch point [km]')
            ax1.set_ylabel('Vertical dist. from\nECI launch point [km]')
        
        else:
            limb_of_earth = plt.Circle((0, 0), gt.R_eq/1000, color='b')
            fig, ax1 = plt.subplots()
            ax1.add_patch(limb_of_earth)
            
            #Compute the ECI coordinates of the true launch point
            GMST_rad = cct.get_current_gmst(self.config['datetime0'],self.times[-1])
            r_true_launch_pt,_ = cct.lla_to_eci(self.lat0_deg,self.lon0_deg,self.alt0_m,np.array([0,0,0]),GMST_rad)
            rx_true_launch_pt = r_true_launch_pt[0]
            ry_true_launch_pt = r_true_launch_pt[1]
            
            if show_flight_phases == True:
                for key in self.phase_t_idx_dict.keys():
                    ax1.plot(self.rx[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]/1000,self.ry[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]/1000,label=key)
            else:
                ax1.plot(self.rx/1000,self.ry/1000,'r', zorder=2)
            
            ax1.scatter(self.rx[0]/1000,self.ry[0]/1000,c='cyan',marker='.',s=50,label='launch point', zorder=3)
            ax1.scatter(rx_true_launch_pt/1000,ry_true_launch_pt/1000,c='tab:pink',marker='.',s=50,label='true launch point', zorder=3)
            if self.altitudes_km[-1] < 2:
                ax1.scatter(self.rx[-1]/1000,self.ry[-1]/1000,c='yellow',marker='.',s=50,label='impact point', zorder=3)
            if self.altitudes_km[-1] > 2:
                ax1.scatter(self.rx[-1]/1000,self.ry[-1]/1000,c='orange',marker='.',s=50,label='final point', zorder=3)
            ax1.set_xlim((min(self.rx) - .25*(max(self.rx)-min(self.rx)))/1000,(max(self.rx) + .25*(max(self.rx)-min(self.rx)))/1000)
            ax1.set_ylim((min(self.ry) - .25*(max(self.ry)-min(self.ry)))/1000,(max(self.ry) + .25*(max(self.ry)-min(self.ry)))/1000)
            ax1.set_xlabel('ECI x-coordinate [km]')
            ax1.set_ylabel('ECI y-coordinate [km]')

        ax1.set_aspect('equal')
        ax1.grid(zorder=1)    
        ax1.set_title(f"{self.config['name']} Trajectory Across Limb of Earth (ECI frame)\nMax gnd rng = {round(max(self.ground_range_km),1)} [km], Max alt = {round(max(self.altitudes_km),1)} [km]", fontsize=12)
        ax1.legend(loc='upper left', bbox_to_anchor=(1.025,1),ncol=1, fontsize=10)
        plt.tight_layout()
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_2d_traj_eci.png', dpi = 300)
        plt.show()

        def get_2d_traj_frame(i):
            if rel_to_launch_point == True:
                #Generate plot of vertical distance vs horizontal distance from ECEF launch point across limb of earth
                limb_of_earth = plt.Circle((0, -gt.R_eq/1000), gt.R_eq/1000, color='b',zorder=0)
                fig, ax1 = plt.subplots()
                ax1.add_patch(limb_of_earth)
                
                #Compute the ECI coordinates of the true launch point
                GMST_rad = cct.get_current_gmst(self.config['datetime0'],self.times[i])
                r_true_launch_pt,_ = cct.lla_to_eci(self.lat0_deg,self.lon0_deg,self.alt0_m,np.array([0,0,0]),GMST_rad)
                rx_true_launch_pt = r_true_launch_pt[0]
                ry_true_launch_pt = r_true_launch_pt[1]
        
                #rotate the coordinates by longitude and GMST to make the plot horizontal
                rotation_angle_rad = -(np.radians(self.lon0_deg) + self.gmst0_rad) + np.pi/2
                R = np.array([[np.cos(rotation_angle_rad),-np.sin(rotation_angle_rad)],[np.sin(rotation_angle_rad),np.cos(rotation_angle_rad)]])
                r_vec = np.array([self.rx,self.ry])
                r_true_launch_pt_vec = np.array([rx_true_launch_pt,ry_true_launch_pt])
                r_vec_new = np.matmul(R,r_vec)
                r_true_launch_pt_vec_new = np.matmul(R,r_true_launch_pt_vec)
                rx_new = r_vec_new[0]
                ry_new = r_vec_new[1]
                rx_true_launch_pt_new = r_true_launch_pt_vec_new[0]
                ry_true_launch_pt_new = r_true_launch_pt_vec_new[1]
                if (rx_new[-1] < 0):
                    rx_new = -rx_new
                    rx_true_launch_pt_new = -rx_true_launch_pt_new
                
                if show_flight_phases == True:
                    for key in self.phase_t_idx_dict.keys():
                        if i < self.phase_t_idx_dict[key][1]+1:
                            ax1.plot(rx_new[self.phase_t_idx_dict[key][0]:i]/1000,(ry_new[self.phase_t_idx_dict[key][0]:i]-gt.R_eq)/1000,label=key,zorder=2)
                        else:
                            ax1.plot(rx_new[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]/1000,(ry_new[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]-gt.R_eq)/1000,label=key,zorder=2)
                else:
                    ax1.plot(rx_new[0:i]/1000,(ry_new[0:i]-gt.R_eq)/1000,'r', zorder=2)
                    
                ax1.scatter(rx_new[0]/1000,(ry_new[0]-gt.R_eq)/1000,c='cyan',marker='.',s=50,label='ECI launch point', zorder=3)
                ax1.scatter(rx_true_launch_pt_new/1000,(ry_true_launch_pt_new-gt.R_eq)/1000,c='tab:pink',marker='.',s=50,label='true launch point', zorder=3)
                if i == len(rx_new)-1 and self.altitudes_km[i] < 2:
                    ax1.scatter(rx_new[-1]/1000,(ry_new[-1]-gt.R_eq)/1000,c='yellow',marker='.',s=50,label='impact point', zorder=3)
                elif i == len(rx_new)-1 and self.altitudes_km[i] > 2:
                    ax1.scatter(rx_new[i]/1000,(ry_new[i]-gt.R_eq)/1000,color='orange',marker='.',s=50,label='final point', zorder=3)
                else:
                    ax1.scatter(rx_new[i]/1000,(ry_new[i]-gt.R_eq)/1000,color='orange',marker='.',s=50, zorder=3)
                    
                ax1.set_xlim((min(rx_new) - .25*(max(rx_new)-min(rx_new)))/1000,(max(rx_new) + .25*(max(rx_new)-min(rx_new)))/1000)
                ax1.set_ylim((min(ry_new-gt.R_eq) - .25*(max(ry_new-gt.R_eq)-min(ry_new-gt.R_eq)))/1000,(max(ry_new-gt.R_eq) + .25*(max(ry_new-gt.R_eq)-min(ry_new-gt.R_eq)))/1000)
                ax1.set_xlabel('Horizontal dist. from ECI launch point [km]')
                ax1.set_ylabel('Vertical dist. from\nECI launch point [km]')
                
            else:
                limb_of_earth = plt.Circle((0, 0), gt.R_eq/1000, color='b',zorder=0)
                fig, ax1 = plt.subplots()
                ax1.add_patch(limb_of_earth)
                
                #Compute the ECI coordinates of the true launch point
                GMST_rad = cct.get_current_gmst(self.config['datetime0'],self.times[i])
                r_true_launch_pt,_ = cct.lla_to_eci(self.lat0_deg,self.lon0_deg,self.alt0_m,np.array([0,0,0]),GMST_rad)
                rx_true_launch_pt = r_true_launch_pt[0]
                ry_true_launch_pt = r_true_launch_pt[1]
                
                if show_flight_phases == True:
                    for key in self.phase_t_idx_dict.keys():
                        if i < self.phase_t_idx_dict[key][1]+1:
                            ax1.plot(self.rx[self.phase_t_idx_dict[key][0]:i]/1000,self.ry[self.phase_t_idx_dict[key][0]:i]/1000,label=key,zorder=2)
                        else:
                            ax1.plot(self.rx[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]/1000,self.ry[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]/1000,label=key,zorder=2)
                else:
                    ax1.plot(self.rx[0:i]/1000,self.ry[0:i]/1000,'r', zorder=2)
                    
                ax1.scatter(self.rx[0]/1000,self.ry[0]/1000,c='cyan',marker='.',s=50,label='ECI launch point', zorder=3)
                ax1.scatter(rx_true_launch_pt/1000,ry_true_launch_pt/1000,c='tab:pink',marker='.',s=50,label='true launch point', zorder=3)
                if i == len(self.rx)-1 and self.altitudes_km[i] < 2:
                    ax1.scatter(self.rx[-1]/1000,self.ry[-1]/1000,c='yellow',marker='.',s=50,label='impact point', zorder=3)
                elif i == len(self.rx)-1 and self.altitudes_km[i] > 2:
                    ax1.scatter(self.rx[i]/1000,self.ry[i]/1000,color='orange',marker='.',s=50,label='final point', zorder=3)
                else:
                    ax1.scatter(self.rx[i]/1000,self.ry[i]/1000,color='orange',marker='.',s=50, zorder=3)
                  
                ax1.set_xlim((min(self.rx) - .25*(max(self.rx)-min(self.rx)))/1000,(max(self.rx) + .25*(max(self.rx)-min(self.rx)))/1000)
                ax1.set_ylim((min(self.ry) - .25*(max(self.ry)-min(self.ry)))/1000,(max(self.ry) + .25*(max(self.ry)-min(self.ry)))/1000)
                ax1.set_xlabel('ECI x-coordinate [km]')
                ax1.set_ylabel('ECI y-coordinate [km]')
            
            ax1.set_aspect('equal')
            ax1.grid(zorder=1)
            whitespace = '  '
            ax1.set_title(f"{whitespace}{self.config['name']} Trajectory Across Limb of Earth (ECI frame){whitespace}\nAt t+{self.times[i]}[s]: alt={round(self.altitudes_km[i],1)}[km], vel={round(np.sqrt(self.v[i,0]**2 + self.v[i,1]**2),1)}[m/s]", fontsize=12)
            ax1.legend(loc='upper left', bbox_to_anchor=(1.025,1),ncol=1, fontsize=10)
            plt.tight_layout()
            
            # Save the plot to an in-memory buffer
            buf = io.BytesIO()
            fig.savefig(buf,format='png',bbox_inches='tight', dpi = 300)
            buf.seek(0)
            plt.close()
            
            return buf
        
        if output_gif == True:
            frames = []
            for i in range(0,len(self.rx),round(len(self.rx)/(gif_frame_count-2))):
                buf = get_2d_traj_frame(i)
                frames.append(Image.open(buf))
        
            #generate final frame
            i = len(self.rx)-1
            buf = get_2d_traj_frame(i)
            frames.append(Image.open(buf))
            
            # Make all frames the same size if they aren't already
            # Assumptions: the last frame is the largest, image dimension changes are on bottom and right sides only
            target_width = frames[-1].size[0]
            target_height = frames[-1].size[1]
            
            padded_frames = []
            for frame in frames:
                canvas = Image.new("RGB", (target_width, target_height), "white")
                canvas.paste(frame, (0, 0))
                padded_frames.append(np.asarray(canvas))
            
            #Save as GIF using imageio.mimsave (analogous to imwrite)
            gif_file_name = fr'\{self.config['name']}_2d_traj_eci_gif.gif'
            gif_file_path = self.config['output_dir'] + gif_file_name
            iio.mimsave(gif_file_path, padded_frames, format='GIF', 
                            duration=ms_per_frame, loop=1) # loop=0 sets an infinite loop
            
        if (output_img or output_gif) and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
    
    def plot_2d_traj_ecef(self,output_img=False,output_gif=False,gif_frame_count=30,ms_per_frame=100,show_flight_phases=False):
        
        #If its a short range trajectory, show plots relative to the launch point
        if max(self.ground_range_km) < 2000:
            rel_to_launch_point = True
        else:
            rel_to_launch_point = False
        
        if rel_to_launch_point == True:
            #Generate plot of vertical distance vs horizontal distance from ECEF launch point across limb of earth
            limb_of_earth = plt.Circle((0, -gt.R_eq/1000), gt.R_eq/1000, color='b',zorder=0)
            fig, ax1 = plt.subplots()
            ax1.add_patch(limb_of_earth)
    
            #rotate the coordinates by longitude and GMST to make the plot horizontal
            rotation_angle_rad = -np.radians(self.lon0_deg) + np.pi/2
            R = np.array([[np.cos(rotation_angle_rad),-np.sin(rotation_angle_rad)],[np.sin(rotation_angle_rad),np.cos(rotation_angle_rad)]])
            r_vec = np.array([self.rx_ecef,self.ry_ecef])
            r_vec_new = np.matmul(R,r_vec)
            rx_new = r_vec_new[0]
            ry_new = r_vec_new[1]
            if (rx_new[-1] < 0):
                rx_new = -rx_new
                
            if show_flight_phases == True:
                for key in self.phase_t_idx_dict.keys():
                    ax1.plot(rx_new[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]/1000,(ry_new[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]-gt.R_eq)/1000,label=key)
            else:
                ax1.plot(rx_new/1000,(ry_new-gt.R_eq)/1000,'r', zorder=2)
                
            ax1.scatter(rx_new[0]/1000,(ry_new[0]-gt.R_eq)/1000,c='cyan',marker='.',s=50,label='launch point', zorder=3)
            if self.altitudes_km[-1] < 2:
                ax1.scatter(rx_new[-1]/1000,(ry_new[-1]-gt.R_eq)/1000,c='yellow',marker='.',s=50,label='impact point', zorder=3)
            elif self.altitudes_km[-1] > 2:
                ax1.scatter(rx_new[-1]/1000,(ry_new[-1]-gt.R_eq)/1000,c='orange',marker='.',s=50,label='final point', zorder=3)
            ax1.set_xlim((min(rx_new) - .25*(max(rx_new)-min(rx_new)))/1000,(max(rx_new) + .25*(max(rx_new)-min(rx_new)))/1000)
            ax1.set_ylim((min(ry_new-gt.R_eq) - .25*(max(ry_new-gt.R_eq)-min(ry_new-gt.R_eq)))/1000,(max(ry_new-gt.R_eq) + .25*(max(ry_new-gt.R_eq)-min(ry_new-gt.R_eq)))/1000)
            ax1.set_xlabel('Horizontal dist. from ECEF launch point [km]')
            ax1.set_ylabel('Vertical dist. from\nECEF launch point [km]')
        else:
            limb_of_earth = plt.Circle((0, 0), gt.R_eq/1000, color='b')
            fig, ax1 = plt.subplots()
            ax1.add_patch(limb_of_earth)
            
            if show_flight_phases == True:
                for key in self.phase_t_idx_dict.keys():
                    ax1.plot(self.rx_ecef[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]/1000,self.ry_ecef[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]/1000,label=key)
            else:
                ax1.plot(self.rx_ecef/1000,self.ry_ecef/1000,'r', zorder=2)
            
            ax1.scatter(self.rx_ecef[0]/1000,self.ry_ecef[0]/1000,c='cyan',marker='.',s=50,label='launch point', zorder=3)
            if self.altitudes_km[-1] < 2:
                ax1.scatter(self.rx_ecef[-1]/1000,self.ry_ecef[-1]/1000,c='yellow',marker='.',s=50,label='impact point', zorder=3)
            if self.altitudes_km[-1] > 2:
                ax1.scatter(self.rx_ecef[-1]/1000,self.ry_ecef[-1]/1000,c='orange',marker='.',s=50,label='final point', zorder=3)
            ax1.set_xlim((min(self.rx_ecef) - .25*(max(self.rx_ecef)-min(self.rx_ecef)))/1000,(max(self.rx_ecef) + .25*(max(self.rx_ecef)-min(self.rx_ecef)))/1000)
            ax1.set_ylim((min(self.ry_ecef) - .25*(max(self.ry_ecef)-min(self.ry_ecef)))/1000,(max(self.ry_ecef) + .25*(max(self.ry_ecef)-min(self.ry_ecef)))/1000)
            ax1.set_xlabel('ECEF x-coordinate [km]')
            ax1.set_ylabel('ECEF y-coordinate [km]')
        
        ax1.set_aspect('equal')
        ax1.grid(zorder=1)    
        ax1.set_title(f"{self.config['name']} Trajectory Across Limb of Earth (ECEF frame)\nMax gnd rng = {round(max(self.ground_range_km),1)} [km], Max alt = {round(max(self.altitudes_km),1)} [km]", fontsize=12)
        ax1.legend(loc='upper left', bbox_to_anchor=(1.025,1),ncol=1, fontsize=10)
        plt.tight_layout()
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_2d_traj_ecef.png', dpi = 300)
        plt.show()

        def get_2d_traj_frame(i):
            if rel_to_launch_point == True:
                #Generate plot of vertical distance vs horizontal distance from ECEF launch point across limb of earth
                limb_of_earth = plt.Circle((0, -gt.R_eq/1000), gt.R_eq/1000, color='b',zorder=0)
                fig, ax1 = plt.subplots()
                ax1.add_patch(limb_of_earth)
        
                #rotate the coordinates by longitude and GMST to make the plot horizontal
                rotation_angle_rad = -np.radians(self.lon0_deg) + np.pi/2
                R = np.array([[np.cos(rotation_angle_rad),-np.sin(rotation_angle_rad)],[np.sin(rotation_angle_rad),np.cos(rotation_angle_rad)]])
                r_vec = np.array([self.rx_ecef,self.ry_ecef])
                r_vec_new = np.matmul(R,r_vec)
                rx_new = r_vec_new[0]
                ry_new = r_vec_new[1]
                if (rx_new[-1] < 0):
                    rx_new = -rx_new
                
                if show_flight_phases == True:
                    for key in self.phase_t_idx_dict.keys():
                        if i < self.phase_t_idx_dict[key][1]+1:
                            ax1.plot(rx_new[self.phase_t_idx_dict[key][0]:i]/1000,(ry_new[self.phase_t_idx_dict[key][0]:i]-gt.R_eq)/1000,label=key,zorder=2)
                        else:
                            ax1.plot(rx_new[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]/1000,(ry_new[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]-gt.R_eq)/1000,label=key,zorder=2)
                else:
                    ax1.plot(rx_new[0:i]/1000,(ry_new[0:i]-gt.R_eq)/1000,'r', zorder=2)
                    
                ax1.scatter(rx_new[0]/1000,(ry_new[0]-gt.R_eq)/1000,c='cyan',marker='.',s=50,label='launch point', zorder=3)
                if i == len(rx_new)-1 and self.altitudes_km[i] < 2:
                    ax1.scatter(rx_new[-1]/1000,(ry_new[-1]-gt.R_eq)/1000,c='yellow',marker='.',s=50,label='impact point', zorder=3)
                elif i == len(rx_new)-1 and self.altitudes_km[i] > 2:
                    ax1.scatter(rx_new[i]/1000,(ry_new[i]-gt.R_eq)/1000,color='orange',marker='.',s=50,label='final point', zorder=3)
                else:
                    ax1.scatter(rx_new[i]/1000,(ry_new[i]-gt.R_eq)/1000,color='orange',marker='.',s=50, zorder=3)
                    
                ax1.set_xlim((min(rx_new) - .25*(max(rx_new)-min(rx_new)))/1000,(max(rx_new) + .25*(max(rx_new)-min(rx_new)))/1000)
                ax1.set_ylim((min(ry_new-gt.R_eq) - .25*(max(ry_new-gt.R_eq)-min(ry_new-gt.R_eq)))/1000,(max(ry_new-gt.R_eq) + .25*(max(ry_new-gt.R_eq)-min(ry_new-gt.R_eq)))/1000)
                ax1.set_xlabel('Horizontal dist. from ECEF launch point [km]')
                ax1.set_ylabel('Vertical dist. from\nECEF launch point [km]')
            else:
                limb_of_earth = plt.Circle((0, 0), gt.R_eq/1000, color='b',zorder=0)
                fig, ax1 = plt.subplots()
                ax1.add_patch(limb_of_earth)
                
                if show_flight_phases == True:
                    for key in self.phase_t_idx_dict.keys():
                        if i < self.phase_t_idx_dict[key][1]+1:
                            ax1.plot(self.rx_ecef[self.phase_t_idx_dict[key][0]:i]/1000,self.ry_ecef[self.phase_t_idx_dict[key][0]:i]/1000,label=key,zorder=2)
                        else:
                            ax1.plot(self.rx_ecef[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]/1000,self.ry_ecef[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]/1000,label=key,zorder=2)
                else:
                    ax1.plot(self.rx_ecef[0:i]/1000,self.ry_ecef[0:i]/1000,'r', zorder=2)
                    
                ax1.scatter(self.rx_ecef[0]/1000,self.ry_ecef[0]/1000,c='cyan',marker='.',s=50,label='launch point', zorder=3)
                if i == len(self.rx_ecef)-1 and self.altitudes_km[i] < 2:
                    ax1.scatter(self.rx_ecef[-1]/1000,self.ry_ecef[-1]/1000,c='yellow',marker='.',s=50,label='impact point', zorder=3)
                elif i == len(self.rx_ecef)-1 and self.altitudes_km[i] > 2:
                    ax1.scatter(self.rx_ecef[i]/1000,self.ry_ecef[i]/1000,color='orange',marker='.',s=50,label='final point', zorder=3)
                else:
                    ax1.scatter(self.rx_ecef[i]/1000,self.ry_ecef[i]/1000,color='orange',marker='.',s=50, zorder=3)
                  
                ax1.set_xlim((min(self.rx_ecef) - .25*(max(self.rx_ecef)-min(self.rx_ecef)))/1000,(max(self.rx_ecef) + .25*(max(self.rx_ecef)-min(self.rx_ecef)))/1000)
                ax1.set_ylim((min(self.ry_ecef) - .25*(max(self.ry_ecef)-min(self.ry_ecef)))/1000,(max(self.ry_ecef) + .25*(max(self.ry_ecef)-min(self.ry_ecef)))/1000)
                ax1.set_xlabel('ECEF x-coordinate [km]')
                ax1.set_ylabel('ECEF y-coordinate [km]')
            
            ax1.set_aspect('equal')
            ax1.grid(zorder=1)
            whitespace = '  '
            ax1.set_title(f"{whitespace}{self.config['name']} Trajectory Across Limb of Earth (ECEF frame){whitespace}\nAt t+{self.times[i]}[s]: alt={round(self.altitudes_km[i],1)}[km], vel={round(np.sqrt(self.v[i,0]**2 + self.v[i,1]**2),1)}[m/s]", fontsize=12)
            ax1.legend(loc='upper left', bbox_to_anchor=(1.025,1),ncol=1, fontsize=10)
            plt.tight_layout()
            
            # Save the plot to an in-memory buffer
            buf = io.BytesIO()
            fig.savefig(buf,format='png',bbox_inches='tight', dpi = 300)
            buf.seek(0)
            plt.close()
            
            return buf
        
        if output_gif == True:
            frames = []
            for i in range(0,len(self.rx_ecef),round(len(self.rx_ecef)/(gif_frame_count-2))):
                buf = get_2d_traj_frame(i)
                frames.append(Image.open(buf))
        
            #generate final frame
            i = len(self.rx_ecef)-1
            buf = get_2d_traj_frame(i)
            frames.append(Image.open(buf))
            
            # Make all frames the same size if they aren't already
            # Assumptions: the last frame is the largest, image dimension changes are on bottom and right sides only
            target_width = frames[-1].size[0]
            target_height = frames[-1].size[1]
            
            padded_frames = []
            for frame in frames:
                canvas = Image.new("RGB", (target_width, target_height), "white")
                canvas.paste(frame, (0, 0))
                padded_frames.append(np.asarray(canvas))
            
            #Save as GIF using imageio.mimsave (analogous to imwrite)
            gif_file_name = fr'\{self.config['name']}_2d_traj_ecef_gif.gif'
            gif_file_path = self.config['output_dir'] + gif_file_name
            iio.mimsave(gif_file_path, padded_frames, format='GIF', 
                            duration=ms_per_frame, loop=1) # loop=0 sets an infinite loop
            
        if (output_img or output_gif) and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True

    def plot_thrust_for_each_stage(self,output_img=False):
        
        for stage in self.config['stages']:
            times_sec = stage.time_and_thrust_arrays[0]
            thrusts_kN = stage.time_and_thrust_arrays[1]/1000
            
            plt.figure()
            plt.plot(times_sec,thrusts_kN)
            
            # Disable scientific notation and top offset numbers on the y-axis
            plt.ticklabel_format(style='plain', axis='y',useOffset=False)
            
            plt.xlabel('time [s]')
            plt.ylabel('thrust [kN]')
            plt.title(f'{self.config['name']} {stage.name} Thrust vs Time')
            plt.grid(True)
            plt.tight_layout()

            if output_img == True:
                plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_{stage.name.replace(' ','')}_thrust.png', dpi = 300)
            plt.show()
        
        if (output_img) and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
            
    def generate_all_plots(self,show_flight_phases=True,output_img=False,output_gif=False,gif_frame_count=50):
        self.plot_alt_vs_ground_range(output_img,show_flight_phases)
        self.plot_alt_vs_time(output_img,show_flight_phases)
        self.plot_fpa_vs_time(output_img)
        self.plot_traj_metrics_eci(output_img)
        self.plot_traj_metrics_ecef(output_img)
        self.plot_dyn_pres_vs_time(output_img,show_flight_phases)
        self.plot_mass_vs_time(output_img,show_flight_phases)
        self.plot_mach_vs_time(output_img,show_flight_phases)
        self.plot_thrust_for_each_stage(output_img)
        self.plot_cd_vs_time(output_img,show_flight_phases)
        self.plot_2d_traj_eci(output_img,output_gif,gif_frame_count,show_flight_phases=True)
        self.plot_2d_traj_ecef(output_img,output_gif,gif_frame_count,show_flight_phases=True)

