# -*- coding: utf-8 -*-
"""
Rocket.py

"""
import os
import sys
import numpy as np
from matplotlib import pyplot as plt
from symbols import deg_symbol, eta_symbol, gamma_symbol
from PySide6 import QtWidgets
from GlobeViewerWindow import GlobeViewerWindow
import numerical_tools as nt
import geophysical_tools as gt
import coordinate_conversion_tools as cct
import matplotlib.ticker as ticker

class RocketStage():
    def __init__(self,
                 name,
                 m_empty,
                 m_propellant,
                 m_dot,
                 v_exhaust,
                 p_exhaust,
                 A_exit,
                 stage_diameter_m,
                 coast_duration_sec,
                 t_steer_start_rel,
                 steer_duration_sec,
                 target_fpa_at_bo_deg):
        
        self.name = name
        self.m_empty = m_empty
        self.m_propellant = m_propellant
        self.m_dot = m_dot
        self.v_exhaust = v_exhaust
        self.p_exhaust = p_exhaust
        self.A_exit = A_exit
        self.stage_diameter_m = stage_diameter_m
        self.t_steer_start_rel = t_steer_start_rel #steer start time relative to engine start, with engine starting AFTER the coast duration
        
        self.target_fpa_at_bo_deg = target_fpa_at_bo_deg
        self.coast_duration_sec = coast_duration_sec
        
        #Derived variables
        self.A = np.pi * (self.stage_diameter_m)**2 / 4
        self.engine_burn_duration_sec = self.m_propellant/self.m_dot #sec, burnout time relative to stage's engine start
        
        if steer_duration_sec > self.engine_burn_duration_sec:
            self.steer_duration_sec = self.engine_burn_duration_sec
        elif steer_duration_sec == -1:
            self.steer_duration_sec = self.engine_burn_duration_sec
        else:
            self.steer_duration_sec = steer_duration_sec
            
        #Variables to be computed upon program execution
        self.required_eta_deg = None #temporary, should be None
        self.fpa_at_bo_deg = None #temporary, should be None
        self.t_start_abs = None #absolute start time, i.e. start time relative to t-0
        self.t_bo_abs = None #absolute burnout time
        self.m_other = None #kg, the mass of all other upper stages and payload
        self.time_and_thrust_arrays = None #N, thrust generated by the engines (for plotting purposes)
        
def null_config():
	return {
        'name'               : 'null',
		'ut1datetime0'       : '2020-01-01 00:12:00', #initial UT1 date-time; format: year-month-day hours:minutes:seconds
		'frame'              : 'J2000',      #standard for earth-centered propagation
		'ode_solver'         : 'rk4',
        'lla0'               : np.array([0,0,0]), #Latitude [degrees], Longitude [degrees], altitude [meters]
        'v0_rel'             : np.array([0,0,0]), #vx [m/s], vy [m/s], vz [m/s]
		'stages'             : [],
        'tspan'              : 0,
        'dt'                 : 0,
        'm_payload'          : 0,
        'launch_azimuth_deg' : 0,
		'output_dir'         : os.getcwd() + r'\Media',
	}

class Rocket():
    def __init__(self,config):
        self.config = null_config()
        for key in config.keys():
            self.config[key] = config[key]
        
        #If the output directory doesn't exist, create it
        if not os.path.exists(self.config['output_dir']): 
            os.mkdir(self.config['output_dir'])
        
        # Make an output directory for the rocket object
        self.config['output_dir'] += f'\\{self.config['name'].replace(' ','')}'
        if not os.path.exists(self.config['output_dir']):
            os.mkdir(self.config['output_dir'])
            
        if abs(self.config['launch_azimuth_deg']) != 90:
            print(f"ERROR: launch azimuth code is not yet generalized... please set launch azimuth to either 90 or -90 degrees! Right now, launch_azimuth_deg = {self.config['launch_azimuth_deg']}")
            sys.exit(1) #end program with exit code 1
            
        #If the coast time of the first stage is set to a non-zero value, warn the user to check the inputs and end the program
        if self.config['stages'][0].coast_duration_sec != 0:
            print(f"ERROR: the {self.config['name']} first stage coast time is {self.config['stages'][0].coast_duration_sec} sec while it should be 0! Please review your stage configurations.")
            sys.exit(1) #end program with exit code 1
        
        self.lat0_deg = self.config['lla0'][0]
        self.lon0_deg = self.config['lla0'][1]
        self.alt0_m = self.config['lla0'][2]
        self.gmst0_rad = cct.ut1_to_gmst(self.config['ut1datetime0'])
        self.r0,self.v0 = cct.lla_to_eci(self.lat0_deg,self.lon0_deg,self.alt0_m,self.config['v0_rel'],self.gmst0_rad)
        
        self.solve_stage_times()
        self.solve_stage_mass_other()
        
        self.m0 = self.config['stages'][0].m_empty + self.config['stages'][0].m_propellant + self.config['stages'][0].m_other
        self.state0 = [self.r0[0],self.r0[1],self.r0[2],self.v0[0],self.v0[1],self.v0[2],self.m0] #initial state vector
        
        states,metrics = nt.propagate_traj(self.state0,
                                           self.config['tspan'],
                                           self.config['dt'],
                                           self.config['stages'],
                                           self.config['launch_azimuth_deg'],
                                           self.config['payload_separates'],
                                           self.config['ode_solver'])
        
        self.rx = states[0]
        self.ry = states[1]
        self.rz = states[2]
        self.vx = states[3]
        self.vy = states[4]
        self.vz = states[5]
        self.m  = states[6]

        self.ax_grav   = metrics[0]
        self.ay_grav   = metrics[1]
        self.az_grav   = metrics[2]
        self.ax_thrust = metrics[3]
        self.ay_thrust = metrics[4]
        self.az_thrust = metrics[5]
        self.ax_drag   = metrics[6]
        self.ay_drag   = metrics[7]
        self.az_drag   = metrics[8]
        self.Cd       = metrics[9]
        self.M        = metrics[10]
        self.fpa_deg  = metrics[11]
        self.eta_deg  = metrics[12]
        self.dyn_pres = metrics[13]
        
        self.ax = self.ax_grav + self.ax_thrust + self.ax_drag
        self.ay = self.ay_grav + self.ay_thrust + self.ay_drag
        self.az = self.az_grav + self.az_thrust + self.az_drag
        
        self.fpa_rad = self.fpa_deg * np.pi/180
        
        self.r = np.column_stack((self.rx,self.ry,self.rz))
        self.v = np.column_stack((self.vx,self.vy,self.vz))
        self.a = np.column_stack((self.ax,self.ay,self.az))
        
        self.times = np.arange(0,self.config['tspan']+self.config['dt']/2,self.config['dt'])[:len(states[0])]

        self.GMSTs = cct.get_gmsts(self.config['ut1datetime0'],self.times)
        self.ut1datetimes = cct.ut1datetime0_and_talos_to_ut1datetimes(self.config['ut1datetime0'],self.times)
        self.first_GMST = cct.get_current_gmst(self.config['ut1datetime0'],self.times[0])
        self.last_GMST = cct.get_current_gmst(self.config['ut1datetime0'],self.times[-1])
        self.r_ecef,self.v_ecef = cct.eci_to_ecef_vec(self.r, self.v, self.GMSTs)
        
        self.rx_ecef = self.r_ecef[:,0]
        self.ry_ecef = self.r_ecef[:,1]
        self.rz_ecef = self.r_ecef[:,2]
        
        #Compute velocity and acceleration magnitudes
        self.v_eci_mag = np.sqrt(self.v[:,0]**2+self.v[:,1]**2+self.v[:,2]**2)
        self.v_ecef_mag = np.sqrt(self.v_ecef[:,0]**2+self.v_ecef[:,1]**2+self.v_ecef[:,2]**2)
        self.a_mag = np.sqrt(self.a[:,0]**2+self.a[:,1]**2+self.a[:,2]**2)

        self.altitudes_km = gt.get_altitudes_km(self.rx,self.ry,self.rz)
        self.ground_ranges_km = gt.get_ground_ranges_km(self.lat0_deg,self.lon0_deg,self.config['ut1datetime0'],self.rx,self.ry,self.rz,self.times)
        self.v_rad = nt.get_radial_vel(self.r,self.v)
        self.v_tan = nt.get_tangential_vel(self.r,self.v)
        self.v_rad_ecef = nt.get_radial_vel(self.r_ecef,self.v_ecef)
        self.v_tan_ecef = nt.get_tangential_vel(self.r_ecef,self.v_ecef)
        self.a_rad = nt.get_radial_accel(self.r,self.a)
        self.a_tan = nt.get_tangential_accel(self.r,self.a)
        
        self.lla = cct.eci_to_lla_vec(self.r,self.GMSTs,degrees=True)
        
        self.stage_count = len(self.config['stages'])
        self.t_bo_final = round(self.config['stages'][self.stage_count-1].t_bo_abs)
        idx_t_bo_final = round(self.t_bo_final/self.config['dt'])
        self.v_tan_bo = self.v_tan[idx_t_bo_final] #tangential velocity at final stage burnout
        
        self.output_msg_displayed_once = False
        self.phase_t_idx_dict = self.get_phase_time_index_dict()
        
        for stage in self.config['stages']:
            stage.time_and_thrust_arrays = self.get_stage_time_and_thrust_arrays(stage)
            
        # Create color dictionaries for plotting
        self.phase_color_dict = {0:'tab:blue',
                            1:'tab:orange',
                            2:'springgreen',
                            3:'tab:red',
                            4:'tab:purple',
                            5:'gold',
                            6:'tab:pink',
                            7:'seagreen',
                            8:'aqua', 
                            9:'tab:olive',
                            10:'fuchsia',
                            11:'tab:brown',
                            12:'teal',
                            13:'tab:gray'}

        self.stage_color_dict = {0:'k',1:'c',2:'m',3:'b',4:'y'}
            
    def get_t_idx(self,t):
        t_idx = round(t/self.config['dt'])
        return t_idx
    
    def get_stage_time_and_thrust_arrays(self,stage):
        t_arr_abs = np.arange(stage.t_start_abs,stage.t_bo_abs+self.config['dt']/2,self.config['dt']) #sec, time array
        T_arr = np.zeros(len(t_arr_abs)) #N, thrust array
        for idx1,t in enumerate(t_arr_abs):
            idx2 = self.get_t_idx(t)
            T_arr[idx1] = stage.v_exhaust * stage.m_dot + (stage.p_exhaust - gt.get_air_pressure(self.altitudes_km[idx2])) * stage.A_exit
        t_arr_rel = np.arange(0,stage.t_bo_abs-stage.t_start_abs+self.config['dt']/2,self.config['dt']) #sec, time array
        return [t_arr_rel,T_arr]
    
    def get_phase_time_index_dict(self,end_is_bo=False):
        #Populate the phase time index dictionary
        phase_t_idx_dict = {}

        for i,stage in enumerate(self.config['stages'],1):
            if i == 1:
                phase_t_idx_dict['vertical flight'] = [self.get_t_idx(stage.t_start_abs),self.get_t_idx(stage.t_start_abs+stage.t_steer_start_rel)]
                phase_t_idx_dict['pitch over'] = [self.get_t_idx(stage.t_start_abs+stage.t_steer_start_rel),self.get_t_idx(stage.t_start_abs+stage.t_steer_start_rel+stage.steer_duration_sec)]
                phase_t_idx_dict['gravity turn'] = [self.get_t_idx(stage.t_start_abs+stage.t_steer_start_rel+stage.steer_duration_sec),self.get_t_idx(stage.t_bo_abs)-1]
            elif i == 2:
                phase_t_idx_dict['MECO, stage sep.'] = [self.get_t_idx(stage.t_start_abs)-1,self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec)]
                phase_t_idx_dict['2nd stage burn'] = [self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec),self.get_t_idx(stage.t_bo_abs)-1]
            elif i == 3:
                phase_t_idx_dict['SECO, stage sep.'] = [self.get_t_idx(stage.t_start_abs)-1,self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec)]
                phase_t_idx_dict['3rd stage burn'] = [self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec),self.get_t_idx(stage.t_bo_abs)-1]
            elif i == 4:
                phase_t_idx_dict['TECO, stage sep.'] = [self.get_t_idx(stage.t_start_abs)-1,self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec)]
                phase_t_idx_dict['3rd stage burn'] = [self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec),self.get_t_idx(stage.t_bo_abs)-1]
            else:
                phase_t_idx_dict[f'S{i} ECO, stage sep.'] = [self.get_t_idx(stage.t_start_abs)-1,self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec)]
                phase_t_idx_dict[f'{i}th stage burn'] = [self.get_t_idx(stage.t_start_abs+stage.coast_duration_sec),self.get_t_idx(stage.t_bo_abs)-1]
            if i == len(self.config['stages']):
                if i == 1:
                    if self.config['payload_separates'] == True:
                        phase_t_idx_dict['MECO, stage sep.'] = [self.get_t_idx(stage.t_bo_abs)-1,self.get_t_idx(stage.t_bo_abs)]
                        phase_t_idx_dict['coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                    else:
                        phase_t_idx_dict['MECO, coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                elif i == 2:
                    if self.config['payload_separates'] == True:
                        phase_t_idx_dict['SECO, stage sep.'] = [self.get_t_idx(stage.t_bo_abs)-1,self.get_t_idx(stage.t_bo_abs)]
                        phase_t_idx_dict['coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                    else:
                        phase_t_idx_dict['SECO, coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                elif i == 3:
                    if self.config['payload_separates'] == True:
                        phase_t_idx_dict['TECO, stage sep.'] = [self.get_t_idx(stage.t_bo_abs)-1,self.get_t_idx(stage.t_bo_abs)]
                        phase_t_idx_dict['coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                    else:
                        phase_t_idx_dict['TECO, coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                elif i == 4:
                    if self.config['payload_separates'] == True:
                        phase_t_idx_dict['FECO, stage sep.'] = [self.get_t_idx(stage.t_bo_abs)-1,self.get_t_idx(stage.t_bo_abs)]
                        phase_t_idx_dict['coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                    else:
                        phase_t_idx_dict['FECO, coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                else:
                    if self.config['payload_separates'] == True:
                        phase_t_idx_dict[f'S{i} ECO, stage sep.'] = [self.get_t_idx(stage.t_bo_abs)-1,self.get_t_idx(stage.t_bo_abs)]
                        phase_t_idx_dict['coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                    else:
                        phase_t_idx_dict[f'S{i} ECO, coast'] = [self.get_t_idx(stage.t_bo_abs),len(self.times)-1]
                    
        return phase_t_idx_dict
        
    def solve_stage_times(self):
        '''
        This solve for the stage start time using the sum of the coast and engine burn durations of previous stages
        '''
        for i,stage in enumerate(self.config['stages']):
            if i == 0 :
                stage.t_start_abs = 0
                stage.t_bo_abs = stage.t_start_abs + stage.coast_duration_sec + stage.engine_burn_duration_sec
            else:
                stage.t_start_abs = self.config['stages'][i-1].t_bo_abs
                stage.t_bo_abs = stage.t_start_abs + stage.coast_duration_sec + stage.engine_burn_duration_sec
            
    def solve_stage_mass_other(self):
        '''
        This solves for the "other mass" which is the sum of the mass of all the stages above the current stage 
        and the payload mass. Thus, in the simulation the total mass to be used upon staging is:
        m_empty + m_propellant + m_other
        '''
        m_payload = self.config['m_payload']
        stages = self.config['stages']
        for i in range(len(stages)):
            stages[i].m_other = m_payload
            for j in range(i+1,len(self.config['stages'])):
                stages[i].m_other += stages[j].m_empty + stages[j].m_propellant
            #print(f'Stage {i+1} m_other = {stages[i].m_other}')
    
    def plot_alt_vs_time(self,output_img=False):
        # Altitude vs time
        fig,ax = plt.subplots()
        
        for i,key in enumerate(self.phase_t_idx_dict.keys()):
            #If the phase is extremely short, like a stage drop, bring the lines to the top visibility layer
            if len(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1])<3:
                zorder=4
            else:
                zorder=3
            plt.plot(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],self.altitudes_km[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],label=key,color=self.phase_color_dict[i],zorder=zorder)
        plt.legend(bbox_to_anchor=(0.5, -.3), loc="upper center",ncol=2)
            
        plt.title(f'{self.config['name']} Rocket Altitude vs Time\nMax altitude = {round(max(self.altitudes_km),1)}[km], Impact at t+{round(self.times[-1],2)}[s]')
        plt.xlabel('Time [sec]')
        plt.ylabel('Altitude [km]')
        plt.grid(True)
        plt.tight_layout()
        
        fig.draw_without_rendering();
        bbox = ax.get_window_extent() #returns bounding box in pixel coordinates
        plt.legend(bbox_to_anchor=(0.5, -.3*bbox.width/bbox.height/3.77), loc="upper center",ncol=2)
            
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_alt_vs_time.png', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True               
        
    def plot_alt_vs_ground_range(self,output_img=False):
        fig,ax = plt.subplots()
        
        for i,key in enumerate(self.phase_t_idx_dict.keys()):
            #If the phase is extremely short, like a stage drop, bring the lines to the top visibility layer
            if len(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1])<3:
                zorder=4
            else:
                zorder=3
            plt.plot(self.ground_ranges_km[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],self.altitudes_km[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],label=key,color=self.phase_color_dict[i],zorder=zorder)
        
        plt.ylim(0, None) 
        plt.title(f'{self.config['name']} Rocket Altitude vs Ground Range\nMax ground range = {round(max(self.ground_ranges_km),1)}[km], Max altitude = {round(max(self.altitudes_km),1)}[km]')
        plt.xlabel('Ground Range [km]')
        plt.ylabel('Altitude [km]')
        plt.grid(True)
        plt.axis('scaled')
        plt.tight_layout()

        fig.draw_without_rendering();
        bbox = ax.get_window_extent() #returns bounding box in pixel coordinates
        plt.legend(bbox_to_anchor=(0.5, -.3*bbox.width/bbox.height/3.77), loc="upper center",ncol=2)
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_alt_vs_ground_range.png', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True

    def plot_fpa_vs_time(self,output_img=False):
        plt.figure()
        plt.plot(self.times,self.fpa_deg,'r',label=f'flight path angle, {gamma_symbol} [{deg_symbol}]')
        plt.plot(self.times,self.eta_deg,'g',label=f'steering angle, {eta_symbol} [{deg_symbol}]')
    
        plt.title(f'{self.config['name']} Pitch Program')
        plt.xlabel('Time [s]')
        plt.ylabel(f'Angle [{deg_symbol}]')
        plt.grid(True)
    
        for i,stage in enumerate(self.config['stages']):
            stage_bo_time = stage.t_start_abs + stage.coast_duration_sec + stage.engine_burn_duration_sec
            plt.scatter(stage_bo_time, stage.target_fpa_at_bo_deg, color=self.stage_color_dict[i],marker='o',s=50,label=f'Stage {i+1} target FPA at $t_{{bo}}$={round(stage_bo_time,1)} [s]',zorder=2)
            x_line_pos = stage.t_start_abs + stage.coast_duration_sec + stage.engine_burn_duration_sec
            plt.axvline(x=x_line_pos, color=self.stage_color_dict[i], linestyle='--', linewidth=1)
        plt.legend()
        plt.tight_layout()
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_fpa_vs_time.png', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
    
    def plot_traj_metrics_eci(self,output_img=False):
        # Position vs time, velocity vs time, and acceleration vs time in ECI frame
        fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(8,4))
        fig.suptitle(f'{self.config['name']} Trajectory Metrics (ECI Frame)', fontsize=16, fontweight="bold",y=1.04)
        
        big_ax = fig.add_subplot(111, frameon=False)
        big_ax.tick_params(labelcolor='none', top=False, bottom=False, left=False, right=False)
        big_ax.grid(False)
    
        ax1.plot(self.times/60, self.ground_ranges_km, label='ground range')
        ax1.plot(self.times/60, self.altitudes_km, label='altitude')
        ax1.set_title(f'Max ground range = {round(max(self.ground_ranges_km),1)} [km]\nMax altitude = {round(max(self.altitudes_km),1)} [km]',fontsize=9)
        ax1.set_xlabel('time [min]')
        ax1.set_ylabel('position [km]')
        ax1.legend(
            loc="upper center", 
            bbox_to_anchor=(0.5, -0.15), 
            ncol=1
            )
        time_tick_spacing_mins = round((self.times[-1]/60)/5)
        ax1.xaxis.set_major_locator(ticker.MultipleLocator(time_tick_spacing_mins))
        ax1.grid()
    
        ax2.plot(self.times/60, self.v_tan/1000, label='tangential vel.')
        ax2.plot(self.times/60, self.v_rad/1000, label='radial vel.')
        ax2.set_title(f'|Max tangential vel| = {round(max(abs(self.v_tan/1000)),1)} [km/s]\n|Max radial vel| = {round(max(abs(self.v_rad/1000)),1)} [km/s]',fontsize=9)
        ax2.set_xlabel('time [min]')
        ax2.set_ylabel('velocity [km/s]')
        ax2.legend(
            loc="upper center", 
            bbox_to_anchor=(0.5, -0.15), 
            ncol=1
            )
        time_tick_spacing_mins = round((self.times[-1]/60)/5)
        ax2.xaxis.set_major_locator(ticker.MultipleLocator(time_tick_spacing_mins))
        ax2.grid()
    
        ax3.plot(self.times/60, self.a_tan, label='tangential accel.')
        ax3.plot(self.times/60, self.a_rad, label='radial accel.')
        ax3.set_title(f'|Max tangential accel| = {round(max(abs(self.a_tan)),1)} [$m/s^2$]\n|Max radial accel| = {round(max(abs(self.a_rad)),1)} [$m/s^2$]',fontsize=9)
        ax3.set_xlabel('time [min]')
        ax3.set_ylabel(r'acceleration [$m/s^2$]')
        ax3.legend(
            loc="upper center", 
            bbox_to_anchor=(0.5, -0.15), 
            ncol=1
            )
        time_tick_spacing_mins = round((self.times[-1]/60)/5)
        ax3.xaxis.set_major_locator(ticker.MultipleLocator(time_tick_spacing_mins))
        ax3.grid()
        
        plt.subplots_adjust(hspace=0.5, wspace=0.6)
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_traj_metrics_eci.png', bbox_inches='tight', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
            
    def plot_traj_metrics_ecef(self,output_img=False):
        # Position vs time, velocity vs time, and acceleration vs time in ECEF frame
        fig, (ax1, ax2, ax3) = plt.subplots(1,3, figsize=(8,4))
        fig.suptitle(f'{self.config['name']} Trajectory Metrics (ECEF Frame)', fontsize=16, fontweight="bold",y=1.04)
        
        big_ax = fig.add_subplot(111, frameon=False)
        big_ax.tick_params(labelcolor='none', top=False, bottom=False, left=False, right=False)
        big_ax.grid(False)
    
        ax1.plot(self.times/60, self.ground_ranges_km, label='ground range')
        ax1.plot(self.times/60, self.altitudes_km, label='altitude')
        ax1.set_title(f'Max ground range = {round(max(self.ground_ranges_km),1)} [km]\nMax altitude = {round(max(self.altitudes_km),1)} [km]',fontsize=9)
        ax1.set_xlabel('time [min]')
        ax1.set_ylabel('position [km]')
        ax1.legend(
            loc="upper center", 
            bbox_to_anchor=(0.5, -0.15), 
            ncol=1
            )
        time_tick_spacing_mins = round((self.times[-1]/60)/5)
        ax1.xaxis.set_major_locator(ticker.MultipleLocator(time_tick_spacing_mins))
        ax1.grid()
    
        ax2.plot(self.times/60, self.v_tan_ecef/1000, label='tangential vel.')
        ax2.plot(self.times/60, self.v_rad_ecef/1000, label='radial vel.')
        ax2.set_title(f'|Max tangential vel| = {round(max(abs(self.v_tan_ecef/1000)),1)} [km/s]\n|Max radial vel| = {round(max(abs(self.v_rad_ecef/1000)),1)} [km/s]',fontsize=9)
        ax2.set_xlabel('time [min]')
        ax2.set_ylabel('velocity [km/s]')
        ax2.legend(
            loc="upper center", 
            bbox_to_anchor=(0.5, -0.15), 
            ncol=1
            )
        time_tick_spacing_mins = round((self.times[-1]/60)/5)
        ax2.xaxis.set_major_locator(ticker.MultipleLocator(time_tick_spacing_mins))
        ax2.grid()
    
        ax3.plot(self.times/60, self.a_tan, label='tangential accel.')
        ax3.plot(self.times/60, self.a_rad, label='radial accel.')
        ax3.set_title(f'|Max tangential accel| = {round(max(abs(self.a_tan)),1)} [$m/s^2$]\n|Max radial accel| = {round(max(abs(self.a_rad)),1)} [$m/s^2$]',fontsize=9)
        ax3.set_xlabel('time [min]')
        ax3.set_ylabel(r'acceleration [$m/s^2$]')
        ax3.legend(
            loc="upper center", 
            bbox_to_anchor=(0.5, -0.15), 
            ncol=1
            )
        time_tick_spacing_mins = round((self.times[-1]/60)/5)
        ax3.xaxis.set_major_locator(ticker.MultipleLocator(time_tick_spacing_mins))
        ax3.grid()
        
        plt.subplots_adjust(hspace=0.5, wspace=1)
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_traj_metrics_ecef.png', bbox_inches='tight', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
    
    def plot_dyn_pres_vs_time(self,output_img=False):
        plt.figure()
        
        for i,key in enumerate(self.phase_t_idx_dict.keys()):
            #If the phase is extremely short, like a stage drop, bring the lines to the top visibility layer
            if len(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1])<3:
                zorder=4
            else:
                zorder=3
            plt.plot(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],self.dyn_pres[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1]/1000,label=key,color=self.phase_color_dict[i],zorder=zorder)
        plt.legend()
        
        plt.title(f'{self.config['name']} Dynamic Pressure vs Time')
        plt.grid(True)
        plt.xlabel('time [s]')
        plt.ylabel(r'dynamic pressure [KPa]')
        plt.tight_layout()
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_dyn_pres_vs_time.png', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
    
    def plot_mass_vs_time(self,output_img=False):
        plt.figure()

        for i,key in enumerate(self.phase_t_idx_dict.keys()):
            #If the phase is extremely short, like a stage drop, bring the lines to the top visibility layer
            if len(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1])<3:
                zorder=4
            else:
                zorder=3
            plt.plot(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],self.m[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],label=key,color=self.phase_color_dict[i],zorder=zorder)
        plt.legend()

        plt.title(f'{self.config['name']} Mass vs Time')
        plt.grid(True)
        plt.xlabel('time [s]')
        plt.ylabel('mass [kg]')
        plt.tight_layout()
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_mass_vs_time.png', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
    
    def plot_mach_vs_time(self,output_img=False):
        plt.figure()
        
        for i,key in enumerate(self.phase_t_idx_dict.keys()):
            #If the phase is extremely short, like a stage drop, bring the lines to the top visibility layer
            if len(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1])<3:
                zorder=4
            else:
                zorder=3
            plt.plot(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],self.M[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],label=key,color=self.phase_color_dict[i],zorder=zorder)
        plt.legend()
            
        plt.xlabel('time [s]')
        plt.ylabel('Mach number')
        plt.title(f'{self.config['name']} Mach Number vs Time')
        plt.grid(True)
        plt.tight_layout()
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_mach_vs_time.png', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
            
    def plot_cd_vs_time(self,output_img=False):
        plt.figure()
        
        for i,key in enumerate(self.phase_t_idx_dict.keys()):
            #If the phase is extremely short, like a stage drop, bring the lines to the top visibility layer
            if len(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1])<3:
                zorder=4
            else:
                zorder=3
            plt.plot(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],self.Cd[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],label=key,color=self.phase_color_dict[i],zorder=zorder)
        plt.legend()
            
        plt.xlabel('time [s]')
        plt.ylabel('drag coefficient')
        plt.title(f'{self.config['name']} Drag Coefficient vs Time')
        plt.grid(True)
        plt.tight_layout()
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_cd_vs_time.png', dpi = 300)
        plt.show()
        
        if output_img and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True

    def plot_thrust_for_each_stage(self,output_img=False):
        
        for stage in self.config['stages']:
            times_sec = stage.time_and_thrust_arrays[0]
            thrusts_kN = stage.time_and_thrust_arrays[1]/1000
            
            plt.figure()
            plt.plot(times_sec,thrusts_kN)
            
            # Disable scientific notation and top offset numbers on the y-axis
            plt.ticklabel_format(style='plain', axis='y',useOffset=False)
            
            plt.xlabel('time [s]')
            plt.ylabel('thrust [kN]')
            plt.title(f'{self.config['name']} {stage.name} Thrust vs Time')
            plt.grid(True)
            plt.tight_layout()
      
            if output_img == True:
                plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_{stage.name.replace(' ','')}_thrust.png', dpi = 300)
            plt.show()
        
        if (output_img) and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
          
    def plot_ecef_vel_vs_time(self,output_img=False):
        plt.figure()
        
        for i,key in enumerate(self.phase_t_idx_dict.keys()):
            #If the phase is extremely short, like a stage drop, bring the lines to the top visibility layer
            if len(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1])<3:
                zorder=4
            else:
                zorder=3
            plt.plot(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],self.v_ecef_mag[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],label=key,color=self.phase_color_dict[i],zorder=zorder)
        plt.legend()
        
        plt.xlabel('time [s]')
        plt.ylabel('$v_{{ECEF}}$[m/s]')
        plt.title(f'{self.config['name']} ECEF Velocity vs Time')
        plt.grid(True)
        plt.tight_layout()
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_ecef_vel_vs_time.png', dpi = 300)
        plt.show()
    
        if (output_img) and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
    
    def plot_eci_vel_vs_time(self,output_img=False):
        plt.figure()
        
        for i,key in enumerate(self.phase_t_idx_dict.keys()):
            #If the phase is extremely short, like a stage drop, bring the lines to the top visibility layer
            if len(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1])<3:
                zorder=4
            else:
                zorder=3
            plt.plot(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],self.v_eci_mag[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],label=key,color=self.phase_color_dict[i],zorder=zorder)
        plt.legend()
        
        plt.xlabel('time [s]')
        plt.ylabel('$v_{{ECI}}$[m/s]')
        plt.title(f'{self.config['name']} ECI Velocity vs Time')
        plt.grid(True)
        plt.tight_layout()
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_eci_vel_vs_time.png', dpi = 300)
        plt.show()
    
        if (output_img) and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
    
    def plot_accel_vs_time(self,output_img=False):
        plt.figure()
        
        for i,key in enumerate(self.phase_t_idx_dict.keys()):
            #If the phase is extremely short, like a stage drop, bring the lines to the top visibility layer
            if len(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1])<3:
                zorder=4
            else:
                zorder=3
            plt.plot(self.times[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],self.a_mag[self.phase_t_idx_dict[key][0]:self.phase_t_idx_dict[key][1]+1],label=key,color=self.phase_color_dict[i],zorder=zorder)
        plt.legend()
        
        plt.xlabel('time [s]')
        plt.ylabel('acceleration [m/$s^2$]')
        plt.title(f'{self.config['name']} Drag Coefficient vs Time')
        plt.grid(True)
        plt.tight_layout()
        
        if output_img == True:
            plt.savefig(self.config['output_dir'] + f'/{self.config['name']}_accel_vs_time.png', dpi = 300)
        plt.show()
    
        if (output_img) and self.output_msg_displayed_once == False:
            print(f'{self.config['name']} media found at:\n{self.config['output_dir']}\n')
            self.output_msg_displayed_once = True
        
    def generate_all_plots(self,output_img=False):
        self.plot_alt_vs_ground_range(output_img)
        self.plot_alt_vs_time(output_img)
        self.plot_fpa_vs_time(output_img)
        self.plot_traj_metrics_eci(output_img)
        self.plot_traj_metrics_ecef(output_img)
        self.plot_dyn_pres_vs_time(output_img)
        self.plot_mass_vs_time(output_img)
        self.plot_mach_vs_time(output_img)
        self.plot_thrust_for_each_stage(output_img)
        self.plot_cd_vs_time(output_img)
        self.plot_ecef_vel_vs_time(output_img)
        self.plot_eci_vel_vs_time(output_img)
        self.plot_accel_vs_time(output_img)
        
    def show_traj_on_globe(self):
        #Show trajectory on the globe
        app = QtWidgets.QApplication.instance()
        if app is None:
            app = QtWidgets.QApplication(sys.argv)
        window = GlobeViewerWindow(self)
        screen = app.primaryScreen()
        if screen:
            window.setGeometry(screen.availableGeometry())
        window.showMaximized()

        sys.exit(app.exec()) if not sys.flags.interactive else app.exec()
